### PR TITLE
Adding more rules

### PR DESCRIPTION
**Pull request by felimartina**
Hello! I'm not sure if you are accepting PRs at this time...
I forked your repo and added many more default rules that were relevant for our company. I was wondering if you would like to take a look at what I did and consider updating the current version of the module to be more flexible and abarcative.

If you want me to create a new module in terraform registry instead that is still fine!

I not only added many more rules, but also made them all optional so that whoever is using the module can cherry pick which rules to use. I updated the README.md file as well...
Let me hear your thoughts and discuss...

### CODE REVIEW

**Comment by brainsik** [comment]
@felimartina Thanks for the PR! I've made a task for us to check it out, but we may not be able to get to it until next week. Appreciate your help!

**Comment by felimartina** [comment]
That's fine, let me hear your thoughts once you take a look at it.
My concern is that it isn't really backwards compatible with the version you published on TF Registry...so I'm not sure on the impact it could have on those that are already using it.
We can always publish another module to the registry but I don't want to end up having thousands of modules that aim to do the same thing.

In regards to my version I only added 15+ aws rules, but it may be wise to go ahead and add all aws config rules available in aws and have them all off by default.

**Comment by qafro1** [comment]
How do I add custom rules

**Comment by felimartina** [comment]
This module does not support custom rules so far...if you are going to create a custom rule (which requires you to code a lambda function) then you are better off using terraform directly

https://www.terraform.io/docs/providers/aws/r/config_config_rule.html

You need to create the lambda, and pass TF the arn and other settings.

BTW...this is a PR, you probably shouldn't be making this question here, but rather opening an issue! thnks!

**Comment by felimartina** [comment]
@dynamike 
Hey there, sorry it tooke me a while to get back to you...crazy week. To your points:

1. As you said, since it is pretty much a rewrite of the entire module, so it would be hard to make separate PRs per feature. Any thoughts?
1. Nice library, haven't heard from it. I will make sure to update readme.md using that library
1. If you look closer, the tags are not required, they are only used when the `required_tags` Config Rule is enabled (`1`)...so nothing to worry about it. You don't even need to provide 6 tags when enabling the rule, you can simply use a few (same for tag values).

We have been doing more work on our side of the moduela adding more AWS managed rules...so a next PR will be even more complex.
Do you think it is better to publish this as a module on its own instead of upgrading your version?

Our goal is to have a comprenhensive module with all AWS managed rules disabled by default and let the users pick just the few rules are relevant for them.
We use this module for different customers with different needs so we need something flexible and maintainable.

thoughts?

**Pull request closed without merging**
