### PR TITLE
terraform 0.12 working

### PR DESCRIPTION
**Pull request by jacoor**
This is battle tested update to 0.12.

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
Looks like this one probably can used instead of this draft: https://github.com/trussworks/terraform-aws-config/pull/11

**Comment by jacoor** [comment]
I tried that draft w/o success.

**Comment by chrisgilmerproj** [comment]
> I tried that draft w/o success.

Oh sorry, I meant that yours is better and mine should probably be closed :) Thanks for doing battle testing here!

**Comment by meabed** [comment]
resolve conflict?

**Comment by dynamike** [comment]
We are currently using this module on 0.12.x and 0.11.x without any modifications, so I'm not sure this PR is needed. It does look like this PR is  doing a little bit more my introducing a region variable. If you want that functionality, could you open a separate PR?

**Pull request closed without merging**
