### PR TITLE
Add an option to add tags and return role for AWS config

### PR DESCRIPTION
**Pull request by smelchior**

### CODE REVIEW

**Comment by esacteksab** [comment]
If you run `make pre_commit_tests` it will update the `README` with the new variable and new output.

**Comment by smelchior** [comment]
sorry for the delay, i updated the PR now :)

**Comment by dynamike** [comment]
```
PASS
ok  	github.com/trussworks/terraform-aws-config/test	404.173s
```

**Comment by smelchior** [comment]
thanks for merging this :) Do you know when you will be able to cut a new release?

**Comment by esacteksab** [comment]
> thanks for merging this :) Do you know when you will be able to cut a new release?

Done! https://github.com/trussworks/terraform-aws-config/releases/tag/v2.5.1

**Pull request merged**
